name: Java CI med Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: todo_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Klona repo
        uses: actions/checkout@v3

      - name: Ställ in JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Vänta på att MySQL startar
        run: |
          echo "Väntar på att MySQL ska starta..."
          sleep 20

      - name: Bygg och kör tester
        run: ./mvnw clean verify
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/tododb
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: root
